# Generated by Django 5.1.5 on 2025-01-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(upload_to='')),
            ],
        ),
    ]
