# Generated by Django 5.1.5 on 2025-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='thumbnail',
            field=models.BinaryField(),
        ),
    ]
