# Generated by Django 5.1.5 on 2025-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_musicmodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='playListModel',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
