# Generated by Django 5.1.5 on 2025-02-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_playlistmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistmodel',
            old_name='url',
            new_name='id',
        ),
    ]
