# Generated by Django 5.1.5 on 2025-05-17 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_rename_url_playlistmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='enable',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
